### ISSUE TITLE
Implement keyset pagination

### ISSUE THREAD

**Issue by samdark** [yiisoft/data#1]
The idea of keyset pagination is simple. Instead of "get me a page 5" you're telling framework get me 10 records since ID = X. On the 1st page X is 0, on the next page it's last ID from the previous page:

```sql
SELECT ...
  FROM ...
 WHERE ...
   AND id < ?last_seen_id
 ORDER BY id DESC
 LIMIT 10
```

# Why

- "Normal" pagination is inefficient on big data sets because `OFFSET 100000 LIMIT 10`  has to fetch 100010 records.
- `count(*)` is inefficient. At least when using InnoDB.

## Considerations

In many cases there's no need to know exact number of a page you are on, total number of pages and total items count.

Therefore visually it can be what Reddit does:

![reddit_pagination](https://user-images.githubusercontent.com/47294/47951001-e9b13680-df6b-11e8-90c1-37dd3b8c7a9e.png)

There's a number of other ways to display data using the same technique:

- Infinite scroll (what Twitter does).
- "Load more" what Facebook does.

Which way to use heavily depends on project type. Social networks are fine with infinite scroll, e-commerce is OK with "Load more.

Still, classic pagination is popular and heavily used so it is a bad idea to remove it from the framework.

## Implementation

Implementation spans over several components:

1. Pagination and data providers. Introduce a way to specify a field or fields on which we're seeking. Consider if we can make it part of base data provider. If not, separate it into its own class.
2. Introduce separate data-widgets for keyset pagination but consider making it an option in existing ones (BaseListView mainly).
3. Introduce a widget that displays "Previous/Next" buttons.

# References

- https://forum.yiiframework.com/t/pagination-without-offset/123570/7
- https://use-the-index-luke.com/no-offset

**Comment by kamarton** [comment]
This is simple way of scanning from database. There are problematic cases that require special planning:

#### not has unique key or unique key is not sort key

Records:

| date | color |
|---|---|
| `2019-01-01` | `red` |
| `2019-01-02` | `green` |
| `2019-01-02` | `orange` |
| `2019-01-02` | `black` |
| `2019-01-03` | `white` |

Scan pages:
```sql
SELECT * FROM ... WHERE 1 ORDER BY date LIMIT 2
// result: red, green
SELECT * FROM ... WHERE date > '2019-01-02' ORDER BY date LIMIT 2
// result: white
// missed records: orange, black
```
For proper operation, you need an optional key that is unique with the sort key.

| date | number | color |
|---|---|---|
| `2019-01-01` | `1` | `red` |
| `2019-01-02` | `1` | `green` |
| `2019-01-02` | `2` | `orange` |
| `2019-01-02` | `3` | `black` |
| `2019-01-03` | `1` | `white` |

Scan pages:
```sql
SELECT * FROM ... WHERE 1 ORDER BY date, number LIMIT 2
// result: red, green
SELECT * FROM ... WHERE date > '2019-01-02' or (date = '2019-01-02' and number > 1) ORDER BY date, number LIMIT 2
// result: orange, black
SELECT * FROM ... WHERE date > '2019-01-02' or (date = '2019-01-02' and number > 3) ORDER BY date, number LIMIT 2
// result: white
// missed records: -
```

#### Scanning is slow (too many records, complicated filtering conditions)

Records

| id | large_text | created_at |
| --- | --- |--- |
| `1` | `apple` | `2019-01-01 00:00:00` |
| `2` | `apple` | `2019-01-01 00:00:01` |
| `3` | `peach` | `2019-01-01 00:00:02` |
| ... `1000000000` | `not apple` | `2019-01-31 23:59:59` |
| `1000000001` | `apple` | `2019-02-01 00:00:00` |
| ... |

Scan pages:
```sql
SELECT * FROM ... WHERE larege_text like `%apple%` order by created_at LIMIT 3
// after 10 mins
// result: 1, 2, 1000000001
```

With date restriction:
```sql
SELECT * FROM ... WHERE larege_text like '%apple%' and date <= '2019-01-01' order by created_at LIMIT 3
// result: 1, 2
SELECT * FROM ... WHERE larege_text like '%apple%' and date <= '2019-01-01' and id > 2 order by created_at LIMIT 3
// result: -
SELECT * FROM ... WHERE larege_text like '%apple%' and date >= '2019-01-02' and date < '2019-01-03' order by created_at LIMIT 3
// result: -
...
SELECT * FROM ... WHERE larege_text like '%apple%' and date >= '2019-02-01' and date < '2019-02-02' order by created_at LIMIT 3
// result: 1000000001
```

In this case, the web request may return to the user and display `currently scanning: xxxx-xx-xx date`. Because the user knows he is only interested in the previous week, he can interrupt the process because he no longer makes sense.

**Comment by samdark** [comment]
Here's draft implementation btw. (not finished): https://github.com/yiisoft/data/pull/3/files#diff-05676246c23f4c54406cfb8f18b388cbR1

**Comment by samdark** [comment]
Implemented.
